name: Upload Extension

on: [push, pull_request]

jobs:
  download-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: download-repository
    steps:
      - run: |
          npm install
          npm install @vscode/vsce

  package:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run:
          node_modules/@vscode/vsce/vsce package --allow-missing-repository

  upload:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: <whatever you want it to be>
          path: <name of extension>-*.vsix # replace name of extension with the name property in package.json
          retention-days: 90