name: Upload Extension

on: [push, pull_request]

jobs:
    Upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                npm i
                npm install @vscode/vsce

            - name: Package Extension
              run: node_modules/@vscode/vsce/vsce package

            - name: Upload extension file
              uses: actions/upload-artifact@v4
              with: 
                path: our-vscode-extension-*.vsix
                name: our-vscode-extension
                retention-days: 90