name: Upload Extension

on: [push, pull_request]

jobs:
  download-repo-install-depends:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm i
          npm i @vscode/vsce

  package-upload:
    runs-on: ubuntu-latest
    needs: download-repo-install-depends
    steps:
      - name: Package Extension
        run: node_modules/@vscode/vsce/vsce package --allow-missing-repository

      - name: Upload extension as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Our VSCode Extension 
          path: our-vscode-extension-*.vsix 
          retention-days: 90